pose_parameters_per_finger:
  thumb: [39, 40, 41, 42, 43, 44, 45, 46, 47]
  index: [3, 4, 5, 6, 7, 8, 9, 10, 11]
  middle: [12, 13, 14, 15, 16, 17, 18, 19, 20]
  ring: [30, 31, 32, 33, 34, 35, 36, 37, 38]
  little: [21, 22, 23, 24, 25, 26, 27, 28, 29]
vertex_indices_per_finger:
  thumb:
  - 724  # tip
  - 706  # middle
  index:
  - 314  # tip
  - 261  # middle
  middle:
  - 426  # tip
  - 399  # middle
  little:
  - 651  # tip
  - 627  # middle
  ring:
  - 534  # tip
  - 509  # middle
joint_indices_per_finger:
  thumb: [13, 14, 15]
  index: [1, 2, 3]
  middle: [4, 5, 6]
  ring: [10, 11, 12]
  little: [7, 8, 9]
tip_vertex_offsets_per_finger:  # marker radius: 0.006
  thumb: [[0.006, 0.006, 0.003], [0.006, 0.006, 0.003]]
  index: [[0, 0.007, 0], [0, 0.007, 0]]
  middle: [[0, 0.007, 0], [0, 0.007, 0]]
  ring: [[0, 0.007, 0], [0, 0.007, 0]]
  little: [[0, 0.007, 0], [0, 0.007, 0]]
action_weights_per_finger:
  thumb:     # roll -l/+r -ext/+flex
      [[0.01, 0.01, 0.01,  # + positive
        0.01, 0.01, 0.01,
        0.01, 0.05, 0.05],
       [0.01, 0.01, 0.01,  # - negative
        0.01, 0.01, 0.01,
        0.01, 0.05, 0.05]]
  index:
      [[0.1, 0.001, 0.001,  # close to palm
        0.1, 0.05, 0.001,  # middle joint
        0.1, 0.05, 0.001],  # tip joint
       [0.1, 0.001, 0.001,
        0.1, 0.05, 0.5,
        0.1, 0.05, 0.05]]
  middle:
      [[0.1, 0.001, 0.001,
        0.1, 0.01, 0.001,
        0.1, 0.01, 0.001],
       [0.1, 0.001, 0.001,
        0.1, 0.05, 0.005,
        0.1, 0.05, 0.005]]
  ring:
      [[0.1, 0.001, 0.001,
        0.1, 0.01, 0.001,
        0.1, 0.01, 0.001],
       [0.1, 0.001, 0.001,
        0.1, 0.05, 0.005,
        0.1, 0.05, 0.005]]
  little:
      [[0.1, 0.001, 0.001,
        0.1, 0.01, 0.001,
        0.1, 0.01, 0.001],
       [0.1, 0.001, 0.001,
        0.1, 0.05, 0.005,
        0.1, 0.05, 0.005]]
